/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\face anim combined export final 8.glb --transform --simplify --weld
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Head(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/head.glb')
  const { actions } = useAnimations(animations, group)

  const animationIndex = 0; // Replace with your desired index count

  // Play the animation based on the index count
  if (actions[animationIndex]) {
    actions[animationIndex].play();
  }


  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="base_setup">
          <group name="face_1" position={[-0.43, -30.56, -36.37]} rotation={[-0.08, 0, 0.03]}>
            <group name="nose" position={[1.32, 49.17, 70.8]} rotation={[2.65, -0.05, 0.02]}>
              <group name="nose001" position={[0, 15.68, 0]} rotation={[-0.01, 0.04, -0.01]} />
            </group>
            <group name="nose004" position={[0.76, 21.41, 72.3]} rotation={[-2.71, -0.01, 0.03]} />
            <group name="earL" position={[43.54, 24.51, 21.67]} rotation={[-0.35, -0.15, -0.19]}>
              <group name="earL001" position={[0, 20.17, 0]} rotation={[-1.01, 0.09, -0.14]} />
              <group name="earL002" position={[1.21, 24.58, -7.22]} rotation={[-2.72, 0.41, -0.1]}>
                <group name="earL003" position={[0, 17.24, 0]} rotation={[-0.83, 0.06, -0.15]} />
              </group>
              <group name="earL004" position={[1.12, -7.16, -6.21]} rotation={[0.77, -0.47, 0.13]} />
            </group>
            <group name="earR" position={[-41.32, 28.01, 18.75]} rotation={[-0.21, 0.17, 0.12]}>
              <group name="earR001" position={[0, 18.04, 0]} rotation={[-1.06, -0.07, 0.11]} />
              <group name="earR002" position={[-1.06, 22.95, -8.82]} rotation={[-2.92, -0.18, -0.01]}>
                <group name="earR003" position={[0, 17.63, 0]} rotation={[-0.81, -0.08, 0.07]} />
              </group>
              <group name="earR004" position={[0.42, -10.5, -1.57]} rotation={[0.1, 0.88, 0.06]} />
            </group>
            <group name="browBL" position={[30.65, 45.45, 58.25]} rotation={[-1, 1.07, 1.81]}>
              <group name="browBL001" position={[0, 6.54, 0]} rotation={[-0.48, -0.11, 0.01]}>
                <group name="browBL002" position={[0, 7.32, 0]} rotation={[-0.64, 0.03, -0.1]}>
                  <group name="browBL003_1" position={[0, 5.81, 0]} rotation={[-0.36, -0.09, 0.1]} />
                </group>
              </group>
            </group>
            <group name="browBR" position={[-28.89, 48.45, 58.65]} rotation={[-1.02, -0.97, -1.91]}>
              <group name="browBR001" position={[0, 6.08, 0]} rotation={[-0.44, 0.02, 0.05]}>
                <group name="browBR002" position={[0, 6.19, 0]} rotation={[-0.64, -0.02, 0.12]}>
                  <group name="browBR003_1" position={[0, 6.56, 0]} rotation={[-0.38, 0.11, -0.15]} />
                </group>
              </group>
            </group>
            <group name="foreheadL" position={[8.39, 82.97, 63.46]} rotation={[2.58, 1.54, 0.36]} />
            <group name="foreheadL001" position={[22.07, 81.74, 57.38]} rotation={[2.71, 1.29, 0.07]} />
            <group name="foreheadL002" position={[31.39, 79.62, 49.75]} rotation={[2.83, 0.7, 0.02]} />
            <group name="templeL" position={[41.55, 74.09, 36.86]} rotation={[-2.88, -0.05, -0.01]} />
            <group name="cheekBL" position={[15.57, 6.81, 62.37]} rotation={[-1, -0.31, -0.77]}>
              <group name="cheekBL001" position={[0, 28.6, 0]} rotation={[0.86, 0.15, 0.21]} />
            </group>
            <group name="browTL" position={[35.32, 46.28, 47.19]} rotation={[1.27, -0.44, 0.37]} />
            <group name="browTL001" position={[31.03, 51.79, 58.27]} rotation={[1.47, -0.38, 0.85]}>
              <group name="browTL002" position={[0, 13.65, 0]} rotation={[0.54, 0.11, 0.46]} />
            </group>
            <group name="browTL003" position={[8.02, 54.72, 69.37]} rotation={[1.97, 0.6, 1.17]} />
            <group name="foreheadR" position={[-4.99, 83.53, 61.35]} rotation={[-2.05, -1.53, 1.31]} />
            <group name="foreheadR001" position={[-17.83, 83.29, 57.06]} rotation={[3.02, -1.3, 0.26]} />
            <group name="foreheadR002" position={[-25.91, 81.51, 49.36]} rotation={[2.98, -0.72, 0.17]} />
            <group name="templeR" position={[-35.57, 75.94, 36.39]} rotation={[-2.9, 0.04, 0.12]} />
            <group name="cheekBR" position={[-12.88, 7.4, 63.55]} rotation={[-1, 0.34, 0.79]}>
              <group name="cheekBR001" position={[0, 27.79, 0]} rotation={[0.61, -0.09, -0.36]} />
            </group>
            <group name="browTR" position={[-33.48, 49.1, 42.05]} rotation={[1.4, 0.43, -0.26]} />
            <group name="browTR001" position={[-29.69, 53.57, 57.2]} rotation={[1.46, 0.34, -0.82]}>
              <group name="browTR002" position={[0, 14.59, 0]} rotation={[0.6, -0.1, -0.6]} />
            </group>
            <group name="browTR003" position={[-6.25, 55.47, 67.56]} rotation={[1.93, -0.56, -1.04]} />
            <group name="eyeL" position={[18.78, 48.1, 57.72]} rotation={[1.65, -0.29, 0]}>
              <group name="lidTL" position={[8.05, 2.88, -0.4]} rotation={[-2.75, 0.85, 2.05]}>
                <group name="lidTL001" position={[0, 4.98, 0]} rotation={[-0.51, 0.8, -0.22]}>
                  <group name="lidTL002" position={[0, 5.13, 0]} rotation={[-0.43, 0.16, -0.29]}>
                    <group name="lidTL003" position={[0, 5.39, 0]} rotation={[-0.12, 0.58, -0.75]} />
                  </group>
                </group>
              </group>
              <group name="lidBL" position={[-6.65, 5.24, 2.95]} rotation={[2.97, 0.19, -1.99]}>
                <group name="lidBL001" position={[0, 4.7, 0]} rotation={[0.21, 0.24, 0.41]}>
                  <group name="lidBL002" position={[0, 5.23, 0]} rotation={[0.23, 0.23, 0.58]}>
                    <group name="lidBL003" position={[0, 5.01, 0]} rotation={[0.19, 0.22, 0.08]} />
                  </group>
                </group>
              </group>
            </group>
            <group name="eyeR" position={[-16.99, 49.7, 56.67]} rotation={[-1.49, 0.16, 3.14]}>
              <group name="lidTR" position={[7.04, 4.85, -2.09]} rotation={[-0.65, 1.04, 1.43]}>
                <group name="lidTR001" position={[0, 4.41, 0]} rotation={[-0.38, -0.68, 0.27]}>
                  <group name="lidTR002" position={[0, 4.92, 0]} rotation={[-0.53, -0.25, 0.4]}>
                    <group name="lidTR003" position={[0, 5.05, 0]} rotation={[-0.1, -0.55, 0.43]} />
                  </group>
                </group>
              </group>
              <group name="lidBR" position={[-7.98, 5.72, -0.41]} rotation={[0.11, 0.4, -1.22]}>
                <group name="lidBR001" position={[0, 4.41, 0]} rotation={[0.09, -0.12, -0.26]}>
                  <group name="lidBR002" position={[0, 4.48, 0]} rotation={[0.12, -0.19, -0.48]}>
                    <group name="lidBR003" position={[0, 4.84, 0]} rotation={[0.12, -0.9, -0.43]} />
                  </group>
                </group>
              </group>
            </group>
            <group name="cheekTL" position={[35.32, 46.28, 47.19]} rotation={[-2.94, -0.88, 1.1]}>
              <group name="cheekTL001" position={[0, 26.18, 0]} rotation={[0.56, 0.48, 1.28]} />
            </group>
            <group name="cheekTR" position={[-33.48, 49.1, 42.05]} rotation={[-3.1, 0.95, -0.88]}>
              <group name="cheekTR001" position={[0, 25.92, 0]} rotation={[0.52, -0.27, -1.23]} />
            </group>
            <group name="teethT" position={[0.01, 13.7, 65.43]} rotation={[-1.5, 0.03, 0]} />
            <group name="jaw_master" position={[0, 45.49, 0]} rotation={[2.3, 0.05, -0.01]}>
              <group name="lipTL" position={[0.81, 77.89, -17.31]} rotation={[2.53, 0.09, -1.16]}>
                <group name="lipTL001_1" position={[0, 8.93, 0]} rotation={[-0.04, -0.19, 0.15]} />
              </group>
              <group name="lipBL" position={[0.27, 79.09, -15.31]} rotation={[2.64, 0.08, -1.29]}>
                <group name="lipBL001_1" position={[0, 8.28, 0]} rotation={[0.08, 0.1, 0.35]} />
              </group>
              <group name="jaw" position={[-0.92, 83.65, 13.91]} rotation={[-1.19, -0.04, -0.03]} />
              <group name="chin" position={[-0.6, 88.02, 2.98]} rotation={[-2.24, 0, -0.05]}>
                <group name="chin001" position={[0, 10.05, 0]} rotation={[1.04, 0.2, -0.02]} />
              </group>
              <group name="lipTR" position={[0.81, 77.89, -17.31]} rotation={[2.53, 0.03, 1.22]}>
                <group name="lipTR001_1" position={[0, 8.46, 0]} rotation={[0.01, 0.2, -0.16]} />
              </group>
              <group name="lipBR" position={[0.27, 79.09, -15.31]} rotation={[2.61, 0.04, 1.31]}>
                <group name="lipBR001_1" position={[0, 6.88, 0]} rotation={[0.18, -0.14, -0.32]} />
              </group>
              <group name="jawL" position={[42.32, 22.81, -15.93]} rotation={[0.68, -0.07, 0.13]}>
                <group name="jawL001" position={[0, 33.33, 0]} rotation={[-0.36, -0.13, 0.52]}>
                  <group name="chinL" position={[0, 38.46, 0]} rotation={[-1.75, -0.42, 0.64]} />
                </group>
              </group>
              <group name="jawR" position={[-38.45, 21.11, -21.12]} rotation={[0.59, 0.01, -0.1]}>
                <group name="jawR001" position={[0, 36.69, 0]} rotation={[-0.25, 0.06, -0.46]}>
                  <group name="chinR" position={[0, 33.39, 0]} rotation={[-1.69, 0.43, -0.63]} />
                </group>
              </group>
              <group name="teethB" position={[-0.66, 78.46, -6.8]} rotation={[2.69, 0.07, 0.01]} />
              <group name="tongue" position={[0.19, 75.02, -13.14]} rotation={[2.6, 0.07, 0.02]}>
                <group name="tongue001" position={[0, 17.15, 0]} rotation={[-0.31, 0, -0.01]}>
                  <group name="tongue002" position={[0, 10.96, 0]} rotation={[-0.68, 0, -0.01]} />
                </group>
              </group>
              <group name="chin_end_glue001" position={[0.08, 83.88, -10.24]} rotation={[-2.3, 0.78, -0.04]} />
            </group>
            <group name="nose_master" position={[0.82, 21.45, 72.21]} rotation={[-2.23, 0.03, -3.14]}>
              <group name="nose002" position={[-0.02, 12.08, -0.06]} rotation={[0.51, 0.11, 3.13]}>
                <group name="nose003" position={[0, 5.02, 0]} rotation={[0.82, 0.1, -0.05]} />
              </group>
              <group name="noseL001" position={[-10.37, -1.12, 6.4]} rotation={[-0.62, -0.23, -0.63]} />
              <group name="noseR001" position={[10.77, -1.25, 5.47]} rotation={[-0.59, 0.26, 0.67]} />
            </group>
            <group name="browBL004" position={[9.84, 49.66, 64.12]} rotation={[-0.64, -1.03, 2.55]}>
              <group name="noseL" position={[0, 5.17, 0]} rotation={[-0.25, -0.53, 0.27]} />
            </group>
            <group name="browBR004" position={[-7.5, 49.48, 63.58]} rotation={[-0.85, 1.07, -2.66]}>
              <group name="noseR" position={[0, 5.63, 0]} rotation={[-0.56, 0.44, 0.13]} />
            </group>
            <group name="brow_glueBL002" position={[21.59, 51.64, 66.04]} rotation={[0.16, 0.75, 0.01]} />
            <group name="brow_glueBR002" position={[-20.43, 53.15, 65.69]} rotation={[0, -0.93, -0.25]} />
            <group name="lid_glueBL002" position={[20.62, 44, 64.59]} rotation={[-2.99, 0.87, 0.02]} />
            <group name="lid_glueBR002" position={[-17.6, 46.1, 64.38]} rotation={[-2.39, -0.84, 0.41]} />
            <group name="cheek_glueTL001" position={[20.47, 31.01, 62.4]} rotation={[-1.49, 0.58, -0.9]} />
            <group name="cheek_glueTR001" position={[-21.93, 31.89, 57.61]} rotation={[-1.64, -0.69, 1.02]} />
            <group name="nose_glueL001" position={[11.39, 25.51, 67.58]} rotation={[3.09, 0.73, 0.18]} />
            <group name="nose_glueR001" position={[-9.77, 25.29, 67.66]} rotation={[3.07, -0.69, -0.18]} />
            <group name="nose_end_glue004" position={[0.62, 17.55, 70.53]} rotation={[-3.07, 0.92, 0]} />
          </group>
        </group>
        <group name="face">
          <group name="root" rotation={[-Math.PI / 2, 0, 0]}>
            <group name="ORG-face" position={[-0.43, 36.37, -30.56]} rotation={[1.49, 0, 0.03]}>
              <group name="ORG-nose" position={[1.32, 49.17, 70.8]} rotation={[2.65, -0.05, 0.02]}>
                <group name="ORG-nose001" position={[0, 15.68, 0]} rotation={[-0.01, 0.04, -0.01]} />
              </group>
              <group name="ORG-nose004" position={[0.76, 21.41, 72.3]} rotation={[-2.71, -0.01, 0.03]} />
              <group name="ORG-earL" position={[43.54, 24.51, 21.67]} rotation={[-0.35, -0.15, -0.19]}>
                <group name="ORG-earL001" position={[0, 20.17, 0]} rotation={[-1.01, 0.09, -0.14]} />
                <group name="ORG-earL002" position={[1.21, 24.58, -7.22]} rotation={[-2.72, 0.41, -0.1]}>
                  <group name="ORG-earL003" position={[0, 17.24, 0]} rotation={[-0.83, 0.06, -0.15]} />
                </group>
                <group name="ORG-earL004" position={[1.12, -7.16, -6.21]} rotation={[0.77, -0.47, 0.13]} />
                <group name="DEF-earL_1" />
                <group name="MCH-ear_handleL001" position={[0, 20.17, 0]} rotation={[-1.01, 0.09, -0.14]} />
                <group name="DEF-earL001_1" position={[0, 20.17, 0]} rotation={[-1.01, 0.09, -0.14]} />
                <group name="MCH-ear_handleL002" position={[1.21, 24.58, -7.22]} rotation={[-2.21, 0.35, -0.17]} />
                <group name="MCH-ear_handleL003" position={[2.84, 8.66, -13.65]} rotation={[3.11, 0.43, 0]} />
                <group name="DEF-earL002_1" position={[1.21, 24.58, -7.22]} rotation={[-2.72, 0.41, -0.1]}>
                  <group name="DEF-earL003_1" position={[0, 17.24, 0]} rotation={[-0.83, 0.06, -0.15]} />
                </group>
                <group name="MCH-ear_handleL004" position={[1.12, -7.16, -6.21]} rotation={[2.18, -0.22, 0.18]} />
                <group name="MCH-ear_end_handleL004" position={[1.12, -7.16, -6.21]} rotation={[0.77, -0.47, 0.13]} />
                <group name="DEF-earL004_1" position={[1.12, -7.16, -6.21]} rotation={[0.77, -0.47, 0.13]} />
                <group name="earL001_1" position={[0, 20.17, 0]} rotation={[0.32, 0.2, 0.13]} />
                <group name="earL002_1" position={[1.21, 24.58, -7.22]} rotation={[0.32, 0.2, 0.13]} />
                <group name="MCH-ear_poffsetL003" position={[2.84, 8.66, -13.65]} rotation={[0.32, 0.2, 0.13]}>
                  <group name="earL003_1" />
                </group>
                <group name="earL004_1" position={[1.12, -7.16, -6.21]} rotation={[0.32, 0.2, 0.13]} />
                <group name="ear_endL004" rotation={[0.32, 0.2, 0.13]} />
              </group>
              <group name="ORG-earR" position={[-41.32, 28.01, 18.75]} rotation={[-0.21, 0.17, 0.12]}>
                <group name="ORG-earR001" position={[0, 18.04, 0]} rotation={[-1.06, -0.07, 0.11]} />
                <group name="ORG-earR002" position={[-1.06, 22.95, -8.82]} rotation={[-2.92, -0.18, -0.01]}>
                  <group name="ORG-earR003" position={[0, 17.63, 0]} rotation={[-0.81, -0.08, 0.07]} />
                </group>
                <group name="ORG-earR004" position={[0.42, -10.5, -1.57]} rotation={[0.1, 0.88, 0.06]} />
                <group name="DEF-earR_1" />
                <group name="MCH-ear_handleR001" position={[0, 18.04, 0]} rotation={[-1.06, -0.07, 0.11]} />
                <group name="DEF-earR001_1" position={[0, 18.04, 0]} rotation={[-1.06, -0.07, 0.11]} />
                <group name="MCH-ear_handleR002" position={[-1.06, 22.95, -8.82]} rotation={[-2.33, -0.17, 0.05]} />
                <group name="MCH-ear_handleR003" position={[-0.89, 5.75, -12.68]} rotation={[2.92, -0.22, -0.04]} />
                <group name="DEF-earR002_1" position={[-1.06, 22.95, -8.82]} rotation={[-2.92, -0.18, -0.01]}>
                  <group name="DEF-earR003_1" position={[0, 17.63, 0]} rotation={[-0.81, -0.08, 0.07]} />
                </group>
                <group name="MCH-ear_handleR004" position={[0.42, -10.5, -1.57]} rotation={[2.07, 0.84, -0.1]} />
                <group name="MCH-ear_end_handleR004" position={[0.42, -10.5, -1.57]} rotation={[0.1, 0.88, 0.06]} />
                <group name="DEF-earR004_1" position={[0.42, -10.5, -1.57]} rotation={[0.1, 0.88, 0.06]} />
                <group name="earR001_1" position={[0, 18.04, 0]} rotation={[0.19, -0.19, -0.08]} />
                <group name="earR002_1" position={[-1.06, 22.95, -8.82]} rotation={[0.19, -0.19, -0.08]} />
                <group name="MCH-ear_poffsetR003" position={[-0.89, 5.75, -12.68]} rotation={[0.19, -0.19, -0.08]}>
                  <group name="earR003_1" />
                </group>
                <group name="earR004_1" position={[0.42, -10.5, -1.57]} rotation={[0.19, -0.19, -0.08]} />
                <group name="ear_endR004" rotation={[0.19, -0.19, -0.08]} />
              </group>
              <group name="ORG-browBL" position={[30.65, 45.45, 58.25]} rotation={[-1, 1.07, 1.81]}>
                <group name="ORG-browBL001" position={[0, 6.54, 0]} rotation={[-0.48, -0.11, 0.01]}>
                  <group name="ORG-browBL002" position={[0, 7.32, 0]} rotation={[-0.64, 0.03, -0.1]}>
                    <group name="ORG-browBL003" position={[0, 5.81, 0]} rotation={[-0.36, -0.09, 0.1]} />
                  </group>
                </group>
              </group>
              <group name="ORG-browBR" position={[-28.89, 48.45, 58.65]} rotation={[-1.02, -0.97, -1.91]}>
                <group name="ORG-browBR001" position={[0, 6.08, 0]} rotation={[-0.44, 0.02, 0.05]}>
                  <group name="ORG-browBR002" position={[0, 6.19, 0]} rotation={[-0.64, -0.02, 0.12]}>
                    <group name="ORG-browBR003" position={[0, 6.56, 0]} rotation={[-0.38, 0.11, -0.15]} />
                  </group>
                </group>
              </group>
              <group name="ORG-foreheadL" position={[8.39, 82.97, 63.46]} rotation={[2.58, 1.54, 0.36]} />
              <group name="ORG-foreheadL001" position={[22.07, 81.74, 57.38]} rotation={[2.71, 1.29, 0.07]} />
              <group name="ORG-foreheadL002" position={[31.39, 79.62, 49.75]} rotation={[2.83, 0.7, 0.02]} />
              <group name="ORG-templeL" position={[41.55, 74.09, 36.86]} rotation={[-2.88, -0.05, -0.01]} />
              <group name="ORG-cheekBL" position={[15.57, 6.81, 62.37]} rotation={[-1, -0.31, -0.77]}>
                <group name="ORG-cheekBL001" position={[0, 28.6, 0]} rotation={[0.86, 0.15, 0.21]} />
              </group>
              <group name="ORG-browTL" position={[35.32, 46.28, 47.19]} rotation={[1.27, -0.44, 0.37]} />
              <group name="ORG-browTL001" position={[31.03, 51.79, 58.27]} rotation={[1.47, -0.38, 0.85]}>
                <group name="ORG-browTL002" position={[0, 13.65, 0]} rotation={[0.54, 0.11, 0.46]} />
              </group>
              <group name="ORG-browTL003" position={[8.02, 54.72, 69.37]} rotation={[1.97, 0.6, 1.17]} />
              <group name="ORG-foreheadR" position={[-4.99, 83.53, 61.35]} rotation={[-2.05, -1.53, 1.31]} />
              <group name="ORG-foreheadR001" position={[-17.83, 83.29, 57.06]} rotation={[3.02, -1.3, 0.26]} />
              <group name="ORG-foreheadR002" position={[-25.91, 81.51, 49.36]} rotation={[2.98, -0.72, 0.17]} />
              <group name="ORG-templeR" position={[-35.57, 75.94, 36.39]} rotation={[-2.9, 0.04, 0.12]} />
              <group name="ORG-cheekBR" position={[-12.88, 7.4, 63.55]} rotation={[-1, 0.34, 0.79]}>
                <group name="ORG-cheekBR001" position={[0, 27.79, 0]} rotation={[0.61, -0.09, -0.36]} />
              </group>
              <group name="ORG-browTR" position={[-33.48, 49.1, 42.05]} rotation={[1.4, 0.43, -0.26]} />
              <group name="ORG-browTR001" position={[-29.69, 53.57, 57.2]} rotation={[1.46, 0.34, -0.82]}>
                <group name="ORG-browTR002" position={[0, 14.59, 0]} rotation={[0.6, -0.1, -0.6]} />
              </group>
              <group name="ORG-browTR003" position={[-6.25, 55.47, 67.56]} rotation={[1.93, -0.56, -1.04]} />
              <group name="ORG-cheekTL" position={[35.32, 46.28, 47.19]} rotation={[-2.94, -0.88, 1.1]}>
                <group name="ORG-cheekTL001" position={[0, 26.18, 0]} rotation={[0.56, 0.48, 1.28]} />
              </group>
              <group name="ORG-cheekTR" position={[-33.48, 49.1, 42.05]} rotation={[-3.1, 0.95, -0.88]}>
                <group name="ORG-cheekTR001" position={[0, 25.92, 0]} rotation={[0.52, -0.27, -1.23]} />
              </group>
              <group name="ORG-teethT" position={[0.01, 13.7, 65.43]} rotation={[-1.5, 0.03, 0]}>
                <group name="DEF-teethT_1" />
              </group>
              <group name="ORG-nose_master" position={[0.82, 21.45, 72.21]} rotation={[-2.23, 0.03, -3.14]}>
                <group name="ORG-nose002" position={[-0.02, 12.08, -0.06]} rotation={[0.51, 0.11, 3.13]}>
                  <group name="ORG-nose003" position={[0, 5.02, 0]} rotation={[0.82, 0.1, -0.05]} />
                </group>
                <group name="ORG-noseL001" position={[-10.37, -1.12, 6.4]} rotation={[-0.62, -0.23, -0.63]} />
                <group name="ORG-noseR001" position={[10.77, -1.25, 5.47]} rotation={[-0.59, 0.26, 0.67]} />
                <group name="MCH-nose_handle002" position={[-0.02, 12.08, -0.06]} rotation={[1.05, 0.1, 3.12]} />
                <group name="MCH-nose_handle003" position={[-0.09, 7.69, -2.51]} rotation={[0, -0.01, -3.13]} />
                <group name="DEF-nose002_1" position={[-0.02, 12.08, -0.06]} rotation={[0.51, 0.11, 3.13]}>
                  <group name="DEF-nose003_1" position={[0, 5.02, 0]} rotation={[0.82, 0.1, -0.05]} />
                </group>
                <group name="MCH-nose_handleL001" position={[-10.37, -1.12, 6.4]} rotation={[-0.62, -0.23, -0.63]} />
                <group name="MCH-nose_end_handleL001" position={[-10.37, -1.12, 6.4]} rotation={[-0.77, 0.04, -1.54]} />
                <group name="DEF-noseL001_1" position={[-10.37, -1.12, 6.4]} rotation={[-0.62, -0.23, -0.63]} />
                <group name="MCH-nose_handleR001" position={[10.77, -1.25, 5.47]} rotation={[-0.59, 0.26, 0.67]} />
                <group name="MCH-nose_end_handleR001" position={[10.77, -1.25, 5.47]} rotation={[-0.7, 0.04, 1.59]} />
                <group name="DEF-noseR001_1" position={[10.77, -1.25, 5.47]} rotation={[-0.59, 0.26, 0.67]} />
                <group name="noseL001_1" position={[-10.37, -1.12, 6.4]} rotation={[-2.23, -0.02, -3.11]}>
                  <group name="ORG-nose_glueL001" rotation={[3.09, 0.73, 0.18]} />
                </group>
                <group name="noseR001_1" position={[10.77, -1.25, 5.47]} rotation={[-2.23, -0.02, -3.11]}>
                  <group name="ORG-nose_glueR001" rotation={[3.07, -0.69, -0.18]} />
                </group>
                <group name="nose002_1" position={[-0.02, 12.08, -0.06]} rotation={[-2.23, -0.02, -3.11]} />
                <group name="nose004_1" position={[0.06, 0.05, -0.09]} rotation={[-2.23, -0.02, -3.11]} />
                <group name="MCH-nose_poffset003" position={[-0.09, 7.69, -2.51]} rotation={[-2.23, -0.02, -3.11]}>
                  <group name="nose003_1" />
                </group>
              </group>
              <group name="ORG-browBL004" position={[9.84, 49.66, 64.12]} rotation={[-0.64, -1.03, 2.55]}>
                <group name="ORG-noseL" position={[0, 5.17, 0]} rotation={[-0.25, -0.53, 0.27]} />
              </group>
              <group name="ORG-browBR004" position={[-7.5, 49.48, 63.58]} rotation={[-0.85, 1.07, -2.66]}>
                <group name="ORG-noseR" position={[0, 5.63, 0]} rotation={[-0.56, 0.44, 0.13]} />
              </group>
              <group name="earL_1" position={[43.54, 24.51, 21.67]} rotation={[-0.35, -0.15, -0.19]} />
              <group name="earR_1" position={[-41.32, 28.01, 18.75]} rotation={[-0.21, 0.17, 0.12]} />
              <group name="eye_masterL" position={[18.78, 47.78, 61.83]} rotation={[1.65, -0.29, 0]}>
                <group name="ORG-eyeL" position={[0, -4.12, 0]}>
                  <group name="ORG-lidTL" position={[8.05, 2.88, -0.4]} rotation={[1.25, -0.93, 1.78]}>
                    <group name="ORG-lidTL001" position={[0, 4.98, 0]} rotation={[0.65, -0.07, -0.18]}>
                      <group name="ORG-lidTL002" position={[0, 5.13, 0]} rotation={[0.41, -0.06, -0.36]}>
                        <group name="ORG-lidTL003" position={[0, 5.39, 0]} rotation={[0.72, -0.1, -0.35]} />
                      </group>
                    </group>
                  </group>
                  <group name="ORG-lidBL" position={[-6.65, 5.24, 2.95]} rotation={[2.03, 0.45, -1.67]}>
                    <group name="ORG-lidBL001" position={[0, 4.7, 0]} rotation={[0.5, 0, 0.01]}>
                      <group name="ORG-lidBL002" position={[0, 5.23, 0]} rotation={[0.67, -0.02, -0.05]}>
                        <group name="ORG-lidBL003" position={[0, 5.01, 0]} rotation={[0.14, 0.02, -0.18]} />
                      </group>
                    </group>
                  </group>
                  <group name="DEF-eye_masterL_1" />
                  <group name="MCH-lid_handleBL" position={[-6.65, 5.24, 2.95]} rotation={[2.03, 0.45, -1.67]} />
                  <group name="MCH-lid_handleBL001" position={[-2.43, 7.26, 3.41]} rotation={[2, 0.18, -1.66]} />
                  <group name="MCH-lid_handleBL002" position={[2.77, 7.17, 2.88]} rotation={[1.95, -0.38, -1.69]} />
                  <group name="MCH-lid_handleBL003" position={[6.48, 4.36, 1.03]} rotation={[1.89, -0.77, -1.81]} />
                  <group name="MCH-lid_end_handleBL003" position={[6.48, 4.36, 1.03]} rotation={[1.87, -0.86, -1.94]} />
                  <group name="MCH-lid_handle_preBL" position={[-6.65, 5.24, 2.95]} rotation={[2.03, 0.45, -1.67]} />
                  <group name="MCH-lid_handle_preBL001" position={[-2.43, 7.26, 3.41]} rotation={[2, 0.18, -1.66]} />
                  <group name="MCH-lid_handle_preBL002" position={[2.77, 7.17, 2.88]} rotation={[1.95, -0.38, -1.69]} />
                  <group name="MCH-lid_handle_preBL003" position={[6.48, 4.36, 1.03]} rotation={[1.89, -0.77, -1.81]} />
                  <group name="MCH-lid_end_handle_preBL003" position={[6.48, 4.36, 1.03]} rotation={[1.87, -0.86, -1.94]} />
                  <group name="DEF-lidBL_1" position={[-6.65, 5.24, 2.95]} rotation={[2.03, 0.45, -1.67]}>
                    <group name="DEF-lidBL001_1" position={[0, 4.7, 0]} rotation={[0.5, 0, 0.01]}>
                      <group name="DEF-lidBL002_1" position={[0, 5.23, 0]} rotation={[0.67, -0.02, -0.05]}>
                        <group name="DEF-lidBL003_1" position={[0, 5.01, 0]} rotation={[0.14, 0.02, -0.18]} />
                      </group>
                    </group>
                  </group>
                  <group name="MCH-lid_handleTL" position={[8.05, 2.88, -0.4]} rotation={[1.25, -0.93, 1.78]} />
                  <group name="MCH-lid_handleTL001" position={[5.13, 6.25, -2.6]} rotation={[1.17, -0.6, 1.62]} />
                  <group name="MCH-lid_handleTL002" position={[0.2, 7.6, -2.94]} rotation={[1.19, -0.06, 1.35]} />
                  <group name="MCH-lid_handleTL003" position={[-4.72, 7.62, -0.72]} rotation={[1.39, 0.46, 0.96]} />
                  <group name="MCH-lid_end_handleTL003" position={[-4.72, 7.62, -0.72]} rotation={[1.75, 0.72, 0.57]} />
                  <group name="MCH-lid_handle_preTL" position={[8.05, 2.88, -0.4]} rotation={[1.25, -0.93, 1.78]} />
                  <group name="MCH-lid_handle_preTL001" position={[5.13, 6.25, -2.6]} rotation={[1.17, -0.6, 1.62]} />
                  <group name="MCH-lid_handle_preTL002" position={[0.2, 7.6, -2.94]} rotation={[1.19, -0.06, 1.35]} />
                  <group name="MCH-lid_handle_preTL003" position={[-4.72, 7.62, -0.72]} rotation={[1.39, 0.46, 0.96]} />
                  <group name="MCH-lid_end_handle_preTL003" position={[-4.72, 7.62, -0.72]} rotation={[1.75, 0.72, 0.57]} />
                  <group name="DEF-lidTL_1" position={[8.05, 2.88, -0.4]} rotation={[1.25, -0.93, 1.78]}>
                    <group name="DEF-lidTL001_1" position={[0, 4.98, 0]} rotation={[0.65, -0.07, -0.18]}>
                      <group name="DEF-lidTL002_1" position={[0, 5.13, 0]} rotation={[0.41, -0.06, -0.36]}>
                        <group name="DEF-lidTL003_1" position={[0, 5.39, 0]} rotation={[0.72, -0.1, -0.35]} />
                      </group>
                    </group>
                  </group>
                  <group name="lidBL_1" position={[-6.65, 5.24, 2.95]} rotation={[-1.65, -0.02, 0.28]} />
                  <group name="MCH-lid_poffsetBL001" position={[-2.43, 7.26, 3.41]} rotation={[-1.65, -0.02, 0.28]}>
                    <group name="lidBL001_1" />
                  </group>
                  <group name="MCH-lid_poffsetBL002" position={[2.77, 7.17, 2.88]} rotation={[-1.65, -0.02, 0.28]}>
                    <group name="lidBL002_1">
                      <group name="ORG-lid_glueBL002" rotation={[-2.99, 0.87, 0.02]} />
                    </group>
                  </group>
                  <group name="MCH-lid_poffsetBL003" position={[6.48, 4.36, 1.03]} rotation={[-1.65, -0.02, 0.28]}>
                    <group name="lidBL003_1" />
                  </group>
                  <group name="lidTL_1" position={[8.05, 2.88, -0.4]} rotation={[-1.65, -0.02, 0.28]} />
                  <group name="MCH-lid_poffsetTL001" position={[5.13, 6.25, -2.6]} rotation={[-1.65, -0.02, 0.28]}>
                    <group name="lidTL001_1" />
                  </group>
                  <group name="MCH-lid_poffsetTL002" position={[0.2, 7.6, -2.94]} rotation={[-1.65, -0.02, 0.28]}>
                    <group name="lidTL002_1" />
                  </group>
                  <group name="MCH-lid_poffsetTL003" position={[-4.72, 7.62, -0.72]} rotation={[-1.65, -0.02, 0.28]}>
                    <group name="lidTL003_1" />
                  </group>
                </group>
                <group name="MCH-eyeL" position={[0, -4.12, 0]}>
                  <group name="DEF-eyeL_1">
                    <group name="DEF-eye_irisL_1" position={[0, 8.37, 0]} />
                  </group>
                </group>
                <group name="MCH-eye_trackL" position={[0, 4.25, 0]} />
              </group>
              <group name="eye_masterR" position={[-17.01, 49.29, 61.92]} rotation={[-1.49, 0.16, 3.14]}>
                <group name="ORG-eyeR" position={[0, -5.27, 0]}>
                  <group name="ORG-lidTR" position={[7.04, 4.85, -2.09]} rotation={[1.39, -0.8, 0.8]}>
                    <group name="ORG-lidTR001" position={[0, 4.41, 0]} rotation={[0.55, 0.04, 0.16]}>
                      <group name="ORG-lidTR002" position={[0, 4.92, 0]} rotation={[0.53, 0.12, 0.46]}>
                        <group name="ORG-lidTR003" position={[0, 5.05, 0]} rotation={[0.41, 0.03, 0.27]} />
                      </group>
                    </group>
                  </group>
                  <group name="ORG-lidBR" position={[-7.98, 5.72, -0.41]} rotation={[1.32, 0.48, -1.8]}>
                    <group name="ORG-lidBR001" position={[0, 4.41, 0]} rotation={[0.28, 0, -0.01]}>
                      <group name="ORG-lidBR002" position={[0, 4.48, 0]} rotation={[0.51, 0, 0.01]}>
                        <group name="ORG-lidBR003" position={[0, 4.84, 0]} rotation={[0.37, 0.03, 0.38]} />
                      </group>
                    </group>
                  </group>
                  <group name="DEF-eye_masterR_1" />
                  <group name="MCH-lid_handleBR" position={[-7.98, 5.72, -0.41]} rotation={[1.32, 0.48, -1.8]} />
                  <group name="MCH-lid_handleBR001" position={[-4.17, 7.41, -1.86]} rotation={[1.29, 0.34, -1.79]} />
                  <group name="MCH-lid_handleBR002" position={[0.11, 7.97, -3.04]} rotation={[1.2, -0.05, -1.77]} />
                  <group name="MCH-lid_handleBR003" position={[4.65, 6.31, -3.37]} rotation={[1.09, -0.43, -1.65]} />
                  <group name="MCH-lid_end_handleBR003" position={[4.65, 6.31, -3.37]} rotation={[1.1, -0.67, -1.42]} />
                  <group name="MCH-lid_handle_preBR" position={[-7.98, 5.72, -0.41]} rotation={[1.32, 0.48, -1.8]} />
                  <group name="MCH-lid_handle_preBR001" position={[-4.17, 7.41, -1.86]} rotation={[1.29, 0.34, -1.79]} />
                  <group name="MCH-lid_handle_preBR002" position={[0.11, 7.97, -3.04]} rotation={[1.2, -0.05, -1.77]} />
                  <group name="MCH-lid_handle_preBR003" position={[4.65, 6.31, -3.37]} rotation={[1.09, -0.43, -1.65]} />
                  <group name="MCH-lid_end_handle_preBR003" position={[4.65, 6.31, -3.37]} rotation={[1.1, -0.67, -1.42]} />
                  <group name="DEF-lidBR_1" position={[-7.98, 5.72, -0.41]} rotation={[1.32, 0.48, -1.8]}>
                    <group name="DEF-lidBR001_1" position={[0, 4.41, 0]} rotation={[0.28, 0, -0.01]}>
                      <group name="DEF-lidBR002_1" position={[0, 4.48, 0]} rotation={[0.51, 0, 0.01]}>
                        <group name="DEF-lidBR003_1" position={[0, 4.84, 0]} rotation={[0.37, 0.03, 0.38]} />
                      </group>
                    </group>
                  </group>
                  <group name="MCH-lid_handleTR" position={[7.04, 4.85, -2.09]} rotation={[1.39, -0.8, 0.8]} />
                  <group name="MCH-lid_handleTR001" position={[4.83, 7.61, 0.54]} rotation={[1.64, -0.57, 1.04]} />
                  <group name="MCH-lid_handleTR002" position={[0.53, 8.7, 2.68]} rotation={[1.87, -0.07, 1.44]} />
                  <group name="MCH-lid_handleTR003" position={[-4.39, 7.84, 1.92]} rotation={[1.83, 0.41, 1.8]} />
                  <group name="MCH-lid_end_handleTR003" position={[-4.39, 7.84, 1.92]} rotation={[1.76, 0.61, 1.98]} />
                  <group name="MCH-lid_handle_preTR" position={[7.04, 4.85, -2.09]} rotation={[1.39, -0.8, 0.8]} />
                  <group name="MCH-lid_handle_preTR001" position={[4.83, 7.61, 0.54]} rotation={[1.64, -0.57, 1.04]} />
                  <group name="MCH-lid_handle_preTR002" position={[0.53, 8.7, 2.68]} rotation={[1.87, -0.07, 1.44]} />
                  <group name="MCH-lid_handle_preTR003" position={[-4.39, 7.84, 1.92]} rotation={[1.83, 0.41, 1.8]} />
                  <group name="MCH-lid_end_handle_preTR003" position={[-4.39, 7.84, 1.92]} rotation={[1.76, 0.61, 1.98]} />
                  <group name="DEF-lidTR_1" position={[7.04, 4.85, -2.09]} rotation={[1.39, -0.8, 0.8]}>
                    <group name="DEF-lidTR001_1" position={[0, 4.41, 0]} rotation={[0.55, 0.04, 0.16]}>
                      <group name="DEF-lidTR002_1" position={[0, 4.92, 0]} rotation={[0.53, 0.12, 0.46]}>
                        <group name="DEF-lidTR003_1" position={[0, 5.05, 0]} rotation={[0.41, 0.03, 0.27]} />
                      </group>
                    </group>
                  </group>
                  <group name="lidBR_1" position={[-7.98, 5.72, -0.41]} rotation={[-1.49, 0.01, -2.99]} />
                  <group name="MCH-lid_poffsetBR001" position={[-4.17, 7.41, -1.86]} rotation={[-1.49, 0.01, -2.99]}>
                    <group name="lidBR001_1" />
                  </group>
                  <group name="MCH-lid_poffsetBR002" position={[0.11, 7.97, -3.04]} rotation={[-1.49, 0.01, -2.99]}>
                    <group name="lidBR002_1">
                      <group name="ORG-lid_glueBR002" rotation={[-2.39, -0.84, 0.41]} />
                    </group>
                  </group>
                  <group name="MCH-lid_poffsetBR003" position={[4.65, 6.31, -3.37]} rotation={[-1.49, 0.01, -2.99]}>
                    <group name="lidBR003_1" />
                  </group>
                  <group name="lidTR_1" position={[7.04, 4.85, -2.09]} rotation={[-1.49, 0.01, -2.99]} />
                  <group name="MCH-lid_poffsetTR001" position={[4.83, 7.61, 0.54]} rotation={[-1.49, 0.01, -2.99]}>
                    <group name="lidTR001_1" />
                  </group>
                  <group name="MCH-lid_poffsetTR002" position={[0.53, 8.7, 2.68]} rotation={[-1.49, 0.01, -2.99]}>
                    <group name="lidTR002_1" />
                  </group>
                  <group name="MCH-lid_poffsetTR003" position={[-4.39, 7.84, 1.92]} rotation={[-1.49, 0.01, -2.99]}>
                    <group name="lidTR003_1" />
                  </group>
                </group>
                <group name="MCH-eyeR" position={[0, -5.27, 0]}>
                  <group name="DEF-eyeR_1">
                    <group name="DEF-eye_irisR_1" position={[0, 9.53, 0]} />
                  </group>
                </group>
                <group name="MCH-eye_trackR" position={[0, 4.26, 0]} />
              </group>
              <group name="jaw_master_1" position={[0, 45.49, 0]} rotation={[2.3, 0.05, -0.01]}>
                <group name="ORG-jaw_master">
                  <group name="ORG-jaw" position={[-0.92, 83.65, 13.91]} rotation={[-1.19, -0.04, -0.03]} />
                  <group name="ORG-chin" position={[-0.6, 88.02, 2.98]} rotation={[-2.24, 0, -0.05]}>
                    <group name="ORG-chin001" position={[0, 10.05, 0]} rotation={[1.04, 0.2, -0.02]} />
                  </group>
                  <group name="ORG-jawL" position={[42.32, 22.81, -15.93]} rotation={[0.68, -0.07, 0.13]}>
                    <group name="ORG-jawL001" position={[0, 33.33, 0]} rotation={[-0.36, -0.13, 0.52]}>
                      <group name="ORG-chinL" position={[0, 38.46, 0]} rotation={[-1.75, -0.42, 0.64]} />
                    </group>
                  </group>
                  <group name="ORG-jawR" position={[-38.45, 21.11, -21.12]} rotation={[0.59, 0.01, -0.1]}>
                    <group name="ORG-jawR001" position={[0, 36.69, 0]} rotation={[-0.25, 0.06, -0.46]}>
                      <group name="ORG-chinR" position={[0, 33.39, 0]} rotation={[-1.69, 0.43, -0.63]} />
                    </group>
                  </group>
                  <group name="ORG-teethB" position={[-0.66, 78.46, -6.8]} rotation={[2.69, 0.07, 0.01]}>
                    <group name="DEF-teethB_1" />
                  </group>
                  <group name="ORG-tongue" position={[0.19, 75.02, -13.14]} rotation={[2.6, 0.07, 0.02]}>
                    <group name="ORG-tongue001" position={[0, 17.15, 0]} rotation={[-0.31, 0, -0.01]}>
                      <group name="ORG-tongue002" position={[0, 10.96, 0]} rotation={[-0.68, 0, -0.01]} />
                    </group>
                  </group>
                  <group name="teethB_1" position={[-0.66, 78.46, -6.8]} rotation={[2.69, 0.07, 0.01]} />
                  <group name="tongue_1" position={[-0.12, 60.28, -4.37]} rotation={[-0.54, 0.02, -0.02]}>
                    <group name="tweak_tongue" position={[0, 17.15, 0]} rotation={[-Math.PI, 0.09, 0]} />
                  </group>
                  <group name="DEF-tongue_1" position={[0.19, 75.02, -13.14]} rotation={[2.6, 0.07, 0.02]}>
                    <group name="DEF-tongue001_1" position={[0, 17.15, 0]} rotation={[-0.31, 0, -0.01]}>
                      <group name="DEF-tongue002_1" position={[0, 10.96, 0]} rotation={[-0.68, 0, -0.01]} />
                    </group>
                  </group>
                  <group name="DEF-jaw_master_1" />
                  <group name="MCH-chin_handle" position={[-0.6, 88.02, 2.98]} rotation={[-1.67, -0.03, -0.04]} />
                  <group name="MCH-chin_handle001" position={[-0.15, 81.83, -4.93]} rotation={[-1.86, 0.19, -0.05]} />
                  <group name="MCH-chin_end_handle001" position={[-0.15, 81.83, -4.93]} rotation={[-1.2, 0.16, -0.04]} />
                  <group name="DEF-chin_1" position={[-0.6, 88.02, 2.98]} rotation={[-2.24, 0, -0.05]}>
                    <group name="DEF-chin001_1" position={[0, 10.05, 0]} rotation={[1.04, 0.2, -0.02]} />
                  </group>
                  <group name="MCH-jaw_handle" position={[-0.92, 83.65, 13.91]} rotation={[-1.19, -0.04, -0.03]} />
                  <group name="DEF-jaw_1" position={[-0.92, 83.65, 13.91]} rotation={[-1.19, -0.04, -0.03]} />
                  <group name="MCH-jaw_handleL" position={[42.32, 22.81, -15.93]} rotation={[0.68, -0.07, 0.13]} />
                  <group name="MCH-jaw_handleL001" position={[37.94, 48.7, 4.6]} rotation={[0.49, -0.16, 0.4]} />
                  <group name="MCH-chin_handleL" position={[16.26, 80.07, 9.64]} rotation={[-0.36, -0.29, 0.7]} />
                  <group name="MCH-chin_end_handleL" position={[16.26, 80.07, 9.64]} rotation={[-1.87, -0.91, 0.05]} />
                  <group name="DEF-jawL_1" position={[42.32, 22.81, -15.93]} rotation={[0.68, -0.07, 0.13]}>
                    <group name="DEF-jawL001_1" position={[0, 33.33, 0]} rotation={[-0.36, -0.13, 0.52]}>
                      <group name="DEF-chinL_1" position={[0, 38.46, 0]} rotation={[-1.75, -0.42, 0.64]} />
                    </group>
                  </group>
                  <group name="MCH-jaw_handleR" position={[-38.45, 21.11, -21.12]} rotation={[0.59, 0.01, -0.1]} />
                  <group name="MCH-jaw_handleR001" position={[-34.64, 51.51, -0.93]} rotation={[0.47, 0.04, -0.32]} />
                  <group name="MCH-chin_handleR" position={[-17.12, 78.8, 7]} rotation={[-0.35, 0.23, -0.74]} />
                  <group name="MCH-chin_end_handleR" position={[-17.12, 78.8, 7]} rotation={[-1.57, 0.95, -0.34]} />
                  <group name="DEF-jawR_1" position={[-38.45, 21.11, -21.12]} rotation={[0.59, 0.01, -0.1]}>
                    <group name="DEF-jawR001_1" position={[0, 36.69, 0]} rotation={[-0.25, 0.06, -0.46]}>
                      <group name="DEF-chinR_1" position={[0, 33.39, 0]} rotation={[-1.69, 0.43, -0.63]} />
                    </group>
                  </group>
                  <group name="tweak_tongue003" position={[-1.17, 52.31, 20.02]} rotation={[1.61, 0.03, 0.05]} />
                  <group name="MCH-tongue001" position={[-0.12, 60.28, -4.37]} rotation={[-0.54, 0.02, -0.02]}>
                    <group name="tweak_tongue001" rotation={[2.83, 0.08, 0.01]} />
                  </group>
                  <group name="MCH-tongue002" position={[-0.12, 60.28, -4.37]} rotation={[-0.54, 0.02, -0.02]}>
                    <group name="tweak_tongue002" position={[-0.16, -10.45, 3.32]} rotation={[2.15, 0.05, 0.05]} />
                  </group>
                  <group name="chin_1" position={[-0.6, 88.02, 2.98]} rotation={[-2.29, 0.02, -0.04]} />
                  <group name="MCH-chin_poffset001" position={[-0.15, 81.83, -4.93]} rotation={[-2.29, 0.02, -0.04]}>
                    <group name="chin001_1" />
                  </group>
                  <group name="chin_end001" position={[0.08, 83.88, -10.24]} rotation={[-2.29, 0.02, -0.04]}>
                    <group name="ORG-chin_end_glue001" rotation={[-0.04, 0.76, 0.02]} />
                  </group>
                  <group name="MCH-chin_end_glue_reparent001" position={[0.27, 79.09, -15.31]} rotation={[-2.29, 0.02, -0.04]} />
                  <group name="jaw_1" position={[-0.92, 83.65, 13.91]} rotation={[-2.29, 0.02, -0.04]} />
                  <group name="jawL001_1" position={[37.94, 48.7, 4.6]} rotation={[-2.29, 0.02, -0.04]} />
                  <group name="chinL_1" position={[16.26, 80.07, 9.64]} rotation={[-2.29, 0.02, -0.04]} />
                  <group name="jawR001_1" position={[-34.64, 51.51, -0.93]} rotation={[-2.29, 0.02, -0.04]} />
                  <group name="chinR_1" position={[-17.12, 78.8, 7]} rotation={[-2.29, 0.02, -0.04]} />
                  <group name="chin_endR" position={[-12.73, 72.72, -14.13]} rotation={[-2.29, 0.02, -0.04]} />
                </group>
              </group>
              <group name="MCH-jaw_master_lock" position={[0, 45.49, 0]} rotation={[2.3, 0.05, -0.01]} />
              <group name="MCH-jaw_master_top" position={[0, 45.49, 0]} rotation={[2.3, 0.05, -0.01]}>
                <group name="ORG-lipTL" position={[0.81, 77.89, -17.31]} rotation={[2.53, 0.09, -1.16]}>
                  <group name="ORG-lipTL001" position={[0, 8.93, 0]} rotation={[-0.04, -0.19, 0.15]} />
                </group>
                <group name="ORG-lipTR" position={[0.81, 77.89, -17.31]} rotation={[2.53, 0.03, 1.22]}>
                  <group name="ORG-lipTR001" position={[0, 8.46, 0]} rotation={[0.01, 0.2, -0.16]} />
                </group>
                <group name="MCH-jaw_master_middle">
                  <group name="jaw_master_mouth" position={[0.54, 78.49, -16.31]} rotation={[2.49, 0.07, -3.09]}>
                    <group name="MCH-jaw_master_top_out" position={[-0.89, -72.5, 34.21]} rotation={[2.5, -0.09, -Math.PI]}>
                      <group name="MCH-lip_armTL" position={[0.81, 77.89, -17.31]} rotation={[2.49, 0.07, -3.09]}>
                        <group name="lipT" rotation={[-1.49, 0.03, -3.12]} />
                      </group>
                    </group>
                    <group name="MCH-jaw_master_bottom_out" position={[-0.89, -72.5, 34.21]} rotation={[2.5, -0.09, -Math.PI]}>
                      <group name="MCH-lip_armBL" position={[0.27, 79.09, -15.31]} rotation={[2.49, 0.07, -3.09]}>
                        <group name="lipB" rotation={[-1.49, 0.03, -3.12]} />
                      </group>
                    </group>
                    <group name="MCH-jaw_master_middle_out" position={[-0.89, -72.5, 34.21]} rotation={[2.5, -0.09, -Math.PI]}>
                      <group name="MCH-lip_end_armBL001" position={[15.44, 72.61, -11.47]} rotation={[2.49, 0.07, -3.09]}>
                        <group name="lip_endL001" rotation={[-1.49, 0.03, -3.12]} />
                      </group>
                      <group name="MCH-lip_end_armBR001" position={[-12.79, 72.74, -14.1]} rotation={[2.49, 0.07, -3.09]}>
                        <group name="lip_endR001" rotation={[-1.49, 0.03, -3.12]} />
                      </group>
                    </group>
                  </group>
                </group>
                <group name="MCH-lip_handleTL" position={[0.81, 77.89, -17.31]} rotation={[2.53, 0.06, -1.53]} />
                <group name="MCH-lip_handleTL001" position={[8.96, 75.36, -14.68]} rotation={[2.35, 0.02, -1.08]} />
                <group name="MCH-lip_end_handleTL001" position={[8.96, 75.36, -14.68]} rotation={[-0.02, 0.96, 0.58]} />
                <group name="DEF-lipTL_1" position={[0.81, 77.89, -17.31]} rotation={[2.53, 0.09, -1.16]}>
                  <group name="DEF-lipTL001_1" position={[0, 8.93, 0]} rotation={[-0.04, -0.19, 0.15]} />
                </group>
                <group name="MCH-lip_handleTR" position={[0.81, 77.89, -17.31]} rotation={[2.53, 0.06, 1.61]} />
                <group name="MCH-lip_handleTR001" position={[-7.14, 75.37, -15.87]} rotation={[2.34, 0.11, 1.16]} />
                <group name="MCH-lip_end_handleTR001" position={[-7.14, 75.37, -15.87]} rotation={[0.06, -0.96, -0.57]} />
                <group name="DEF-lipTR_1" position={[0.81, 77.89, -17.31]} rotation={[2.53, 0.03, 1.22]}>
                  <group name="DEF-lipTR001_1" position={[0, 8.46, 0]} rotation={[0.01, 0.2, -0.16]} />
                </group>
              </group>
              <group name="MCH-jaw_master_bottom" position={[0, 45.49, 0]} rotation={[2.3, 0.05, -0.01]}>
                <group name="ORG-lipBL" position={[0.27, 79.09, -15.31]} rotation={[2.64, 0.08, -1.29]}>
                  <group name="ORG-lipBL001" position={[0, 8.28, 0]} rotation={[0.08, 0.1, 0.35]} />
                </group>
                <group name="ORG-lipBR" position={[0.27, 79.09, -15.31]} rotation={[2.61, 0.04, 1.31]}>
                  <group name="ORG-lipBR001" position={[0, 6.88, 0]} rotation={[0.18, -0.14, -0.32]} />
                </group>
                <group name="MCH-lip_handleBL" position={[0.27, 79.09, -15.31]} rotation={[2.64, 0.06, -1.54]} />
                <group name="MCH-lip_handleBL001" position={[8.2, 77.38, -13.66]} rotation={[2.73, 0.06, -1.11]} />
                <group name="MCH-lip_end_handleBL001" position={[8.2, 77.38, -13.66]} rotation={[-2.86, -0.5, -0.37]} />
                <group name="DEF-lipBL_1" position={[0.27, 79.09, -15.31]} rotation={[2.64, 0.08, -1.29]}>
                  <group name="DEF-lipBL001_1" position={[0, 8.28, 0]} rotation={[0.08, 0.1, 0.35]} />
                </group>
                <group name="MCH-lip_handleBR" position={[0.27, 79.09, -15.31]} rotation={[2.61, 0.06, 1.61]} />
                <group name="MCH-lip_handleBR001" position={[-6.36, 77.43, -14.63]} rotation={[2.75, 0.1, 1.12]} />
                <group name="MCH-lip_end_handleBR001" position={[-6.36, 77.43, -14.63]} rotation={[-2.85, 0.66, 0.4]} />
                <group name="DEF-lipBR_1" position={[0.27, 79.09, -15.31]} rotation={[2.61, 0.04, 1.31]}>
                  <group name="DEF-lipBR001_1" position={[0, 6.88, 0]} rotation={[0.18, -0.14, -0.32]} />
                </group>
              </group>
              <group name="nose_master_1" position={[0.82, 21.45, 72.21]} rotation={[-2.23, 0.03, -3.14]} />
              <group name="teethT_1" position={[0.01, 13.7, 65.43]} rotation={[-1.5, 0.03, 0]} />
              <group name="MCH-brow_handleBL" position={[30.65, 45.45, 58.25]} rotation={[-1, 1.07, 1.81]} />
              <group name="MCH-brow_handleBL001" position={[27.59, 49.29, 62.58]} rotation={[-0.76, 0.83, 1.63]} />
              <group name="MCH-brow_handleBL002" position={[21.59, 51.64, 66.04]} rotation={[-0.71, 0.32, 1.59]} />
              <group name="MCH-brow_handleBL003" position={[15.79, 51.64, 65.75]} rotation={[-0.64, -0.23, 1.61]} />
              <group name="DEF-browBL_1" position={[30.65, 45.45, 58.25]} rotation={[-1, 1.07, 1.81]}>
                <group name="DEF-browBL001_1" position={[0, 6.54, 0]} rotation={[-0.48, -0.11, 0.01]}>
                  <group name="DEF-browBL002_1" position={[0, 7.32, 0]} rotation={[-0.64, 0.03, -0.1]}>
                    <group name="DEF-browBL003_1" position={[0, 5.81, 0]} rotation={[-0.36, -0.09, 0.1]} />
                  </group>
                </group>
              </group>
              <group name="MCH-brow_handleBL004" position={[9.84, 49.66, 64.12]} rotation={[-0.99, -0.71, 1.86]} />
              <group name="MCH-nose_handleL" position={[8.34, 44.75, 64.67]} rotation={[-0.1, -0.6, -3.06]} />
              <group name="MCH-nose_end_handleL" position={[8.34, 44.75, 64.67]} rotation={[-0.04, -0.59, -2.95]} />
              <group name="DEF-browBL004_1" position={[9.84, 49.66, 64.12]} rotation={[-0.64, -1.03, 2.55]}>
                <group name="DEF-noseL_1" position={[0, 5.17, 0]} rotation={[-0.25, -0.53, 0.27]} />
              </group>
              <group name="MCH-brow_handleBR" position={[-28.89, 48.45, 58.65]} rotation={[-1.02, -0.97, -1.91]} />
              <group name="MCH-brow_handleBR001" position={[-25.64, 51.44, 62.84]} rotation={[-0.88, -0.76, -1.78]} />
              <group name="MCH-brow_handleBR002" position={[-20.43, 53.15, 65.69]} rotation={[-0.78, -0.22, -1.64]} />
              <group name="MCH-brow_handleBR003" position={[-13.89, 52.69, 65.29]} rotation={[-0.67, 0.29, -1.69]} />
              <group name="DEF-browBR_1" position={[-28.89, 48.45, 58.65]} rotation={[-1.02, -0.97, -1.91]}>
                <group name="DEF-browBR001_1" position={[0, 6.08, 0]} rotation={[-0.44, 0.02, 0.05]}>
                  <group name="DEF-browBR002_1" position={[0, 6.19, 0]} rotation={[-0.64, -0.02, 0.12]}>
                    <group name="DEF-browBR003_1" position={[0, 6.56, 0]} rotation={[-0.38, 0.11, -0.15]} />
                  </group>
                </group>
              </group>
              <group name="MCH-brow_handleBR004" position={[-7.5, 49.48, 63.58]} rotation={[-1.24, 0.78, -1.86]} />
              <group name="MCH-nose_handleR" position={[-6.25, 44.47, 65.82]} rotation={[-0.1, 0.66, 3.02]} />
              <group name="MCH-nose_end_handleR" position={[-6.25, 44.47, 65.82]} rotation={[0.04, 0.64, 2.92]} />
              <group name="DEF-browBR004_1" position={[-7.5, 49.48, 63.58]} rotation={[-0.85, 1.07, -2.66]}>
                <group name="DEF-noseR_1" position={[0, 5.63, 0]} rotation={[-0.56, 0.44, 0.13]} />
              </group>
              <group name="MCH-brow_handleTL" position={[35.32, 46.28, 47.19]} rotation={[0.42, -0.64, 0.14]} />
              <group name="DEF-browTL_1" position={[35.32, 46.28, 47.19]} rotation={[1.27, -0.44, 0.37]} />
              <group name="MCH-brow_handleTL001" position={[31.03, 51.79, 58.27]} rotation={[1.39, -0.44, 0.62]} />
              <group name="MCH-brow_handleTL002" position={[21.54, 56.49, 66.89]} rotation={[1.65, -0.16, 1.14]} />
              <group name="DEF-browTL001_1" position={[31.03, 51.79, 58.27]} rotation={[1.47, -0.38, 0.85]}>
                <group name="DEF-browTL002_1" position={[0, 13.65, 0]} rotation={[0.54, 0.11, 0.46]} />
              </group>
              <group name="MCH-brow_handleTL003" position={[8.02, 54.72, 69.37]} rotation={[1.85, 0.29, 1.3]} />
              <group name="MCH-brow_end_handleTL003" position={[8.02, 54.72, 69.37]} rotation={[1.88, -0.01, 1.71]} />
              <group name="DEF-browTL003_1" position={[8.02, 54.72, 69.37]} rotation={[1.97, 0.6, 1.17]} />
              <group name="MCH-brow_handleTR" position={[-33.48, 49.1, 42.05]} rotation={[0.25, 0.62, -0.07]} />
              <group name="DEF-browTR_1" position={[-33.48, 49.1, 42.05]} rotation={[1.4, 0.43, -0.26]} />
              <group name="MCH-brow_handleTR001" position={[-29.69, 53.57, 57.2]} rotation={[1.42, 0.36, -0.52]} />
              <group name="MCH-brow_handleTR002" position={[-19.66, 58.17, 66.74]} rotation={[1.7, 0.13, -1.17]} />
              <group name="DEF-browTR001_1" position={[-29.69, 53.57, 57.2]} rotation={[1.46, 0.34, -0.82]}>
                <group name="DEF-browTR002_1" position={[0, 14.59, 0]} rotation={[0.6, -0.1, -0.6]} />
              </group>
              <group name="MCH-brow_handleTR003" position={[-6.25, 55.47, 67.56]} rotation={[1.83, -0.35, -1.3]} />
              <group name="MCH-brow_end_handleTR003" position={[-6.25, 55.47, 67.56]} rotation={[1.75, -0.03, -1.44]} />
              <group name="DEF-browTR003_1" position={[-6.25, 55.47, 67.56]} rotation={[1.93, -0.56, -1.04]} />
              <group name="MCH-cheek_handleBL" position={[15.57, 6.81, 62.37]} rotation={[-1, -0.31, -0.77]} />
              <group name="MCH-cheek_handleBL001" position={[34.52, 23.05, 48.4]} rotation={[-0.63, -0.5, -0.5]} />
              <group name="DEF-cheekBL_1" position={[15.57, 6.81, 62.37]} rotation={[-1, -0.31, -0.77]}>
                <group name="DEF-cheekBL001_1" position={[0, 28.6, 0]} rotation={[0.86, 0.15, 0.21]} />
              </group>
              <group name="MCH-cheek_handleBR" position={[-12.88, 7.4, 63.55]} rotation={[-1, 0.34, 0.79]} />
              <group name="MCH-cheek_handleBR001" position={[-31.38, 23.63, 50.65]} rotation={[-0.75, 0.55, 0.49]} />
              <group name="DEF-cheekBR_1" position={[-12.88, 7.4, 63.55]} rotation={[-1, 0.34, 0.79]}>
                <group name="DEF-cheekBR001_1" position={[0, 27.79, 0]} rotation={[0.61, -0.09, -0.36]} />
              </group>
              <group name="MCH-cheek_handleTL" position={[35.32, 46.28, 47.19]} rotation={[-2.94, -0.88, 1.1]} />
              <group name="MCH-cheek_handleTL001" position={[20.47, 31.01, 62.4]} rotation={[-2.94, -0.57, 1.64]} />
              <group name="MCH-cheek_end_handleTL001" position={[20.47, 31.01, 62.4]} rotation={[-3.14, -0.18, 2.41]} />
              <group name="DEF-cheekTL_1" position={[35.32, 46.28, 47.19]} rotation={[-2.94, -0.88, 1.1]}>
                <group name="DEF-cheekTL001_1" position={[0, 26.18, 0]} rotation={[0.56, 0.48, 1.28]} />
              </group>
              <group name="MCH-cheek_handleTR" position={[-33.48, 49.1, 42.05]} rotation={[-3.1, 0.95, -0.88]} />
              <group name="MCH-cheek_handleTR001" position={[-21.93, 31.89, 57.61]} rotation={[-2.83, 0.72, -1.65]} />
              <group name="MCH-cheek_end_handleTR001" position={[-21.93, 31.89, 57.61]} rotation={[-2.99, 0.38, -2.25]} />
              <group name="DEF-cheekTR_1" position={[-33.48, 49.1, 42.05]} rotation={[-3.1, 0.95, -0.88]}>
                <group name="DEF-cheekTR001_1" position={[0, 25.92, 0]} rotation={[0.52, -0.27, -1.23]} />
              </group>
              <group name="MCH-forehead_handleL" position={[8.39, 82.97, 63.46]} rotation={[2.58, 1.54, 0.36]} />
              <group name="MCH-forehead_end_handleL" position={[8.39, 82.97, 63.46]} rotation={[2.58, 1.54, 0.36]} />
              <group name="DEF-foreheadL_1" position={[8.39, 82.97, 63.46]} rotation={[2.58, 1.54, 0.36]} />
              <group name="MCH-forehead_handleL001" position={[22.07, 81.74, 57.38]} rotation={[2.71, 1.29, 0.07]} />
              <group name="MCH-forehead_end_handleL001" position={[22.07, 81.74, 57.38]} rotation={[2.71, 1.29, 0.07]} />
              <group name="DEF-foreheadL001_1" position={[22.07, 81.74, 57.38]} rotation={[2.71, 1.29, 0.07]} />
              <group name="MCH-forehead_handleL002" position={[31.39, 79.62, 49.75]} rotation={[2.83, 0.7, 0.02]} />
              <group name="MCH-forehead_end_handleL002" position={[31.39, 79.62, 49.75]} rotation={[2.83, 0.7, 0.02]} />
              <group name="DEF-foreheadL002_1" position={[31.39, 79.62, 49.75]} rotation={[2.83, 0.7, 0.02]} />
              <group name="MCH-forehead_handleR" position={[-4.99, 83.53, 61.35]} rotation={[-2.05, -1.53, 1.31]} />
              <group name="MCH-forehead_end_handleR" position={[-4.99, 83.53, 61.35]} rotation={[-2.05, -1.53, 1.31]} />
              <group name="DEF-foreheadR_1" position={[-4.99, 83.53, 61.35]} rotation={[-2.05, -1.53, 1.31]} />
              <group name="MCH-forehead_handleR001" position={[-17.83, 83.29, 57.06]} rotation={[3.02, -1.3, 0.26]} />
              <group name="MCH-forehead_end_handleR001" position={[-17.83, 83.29, 57.06]} rotation={[3.02, -1.3, 0.26]} />
              <group name="DEF-foreheadR001_1" position={[-17.83, 83.29, 57.06]} rotation={[3.02, -1.3, 0.26]} />
              <group name="MCH-forehead_handleR002" position={[-25.91, 81.51, 49.36]} rotation={[2.98, -0.72, 0.17]} />
              <group name="MCH-forehead_end_handleR002" position={[-25.91, 81.51, 49.36]} rotation={[2.98, -0.72, 0.17]} />
              <group name="DEF-foreheadR002_1" position={[-25.91, 81.51, 49.36]} rotation={[2.98, -0.72, 0.17]} />
              <group name="MCH-nose_handle" position={[1.32, 49.17, 70.8]} rotation={[2.65, -0.05, 0.02]} />
              <group name="MCH-nose_handle001" position={[0.95, 35.36, 78.2]} rotation={[2.65, -0.01, 0.02]} />
              <group name="DEF-nose_1" position={[1.32, 49.17, 70.8]} rotation={[2.65, -0.05, 0.02]}>
                <group name="DEF-nose001_1" position={[0, 15.68, 0]} rotation={[-0.01, 0.04, -0.01]} />
              </group>
              <group name="MCH-nose_handle004" position={[0.76, 21.41, 72.3]} rotation={[-2.19, 0.01, 0.02]} />
              <group name="MCH-nose_end_handle004" position={[0.76, 21.41, 72.3]} rotation={[-2.71, -0.01, 0.03]} />
              <group name="DEF-nose004_1" position={[0.76, 21.41, 72.3]} rotation={[-2.71, -0.01, 0.03]} />
              <group name="MCH-temple_handleL" position={[41.55, 74.09, 36.86]} rotation={[-2.88, -0.05, -0.01]} />
              <group name="MCH-temple_end_handleL" position={[41.55, 74.09, 36.86]} rotation={[-2.88, -0.05, -0.01]} />
              <group name="DEF-templeL_1" position={[41.55, 74.09, 36.86]} rotation={[-2.88, -0.05, -0.01]} />
              <group name="MCH-temple_handleR" position={[-35.57, 75.94, 36.39]} rotation={[-2.9, 0.04, 0.12]} />
              <group name="MCH-temple_end_handleR" position={[-35.57, 75.94, 36.39]} rotation={[-2.9, 0.04, 0.12]} />
              <group name="DEF-templeR_1" position={[-35.57, 75.94, 36.39]} rotation={[-2.9, 0.04, 0.12]} />
              <group name="browBL_1" position={[30.65, 45.45, 58.25]} />
              <group name="MCH-brow_poffsetBL001" position={[27.59, 49.29, 62.58]}>
                <group name="browBL001_1" />
              </group>
              <group name="MCH-brow_poffsetBL002" position={[21.59, 51.64, 66.04]}>
                <group name="browBL002_1">
                  <group name="ORG-brow_glueBL002" rotation={[0.16, 0.75, 0.01]} />
                </group>
              </group>
              <group name="MCH-brow_poffsetBL003" position={[15.79, 51.64, 65.75]}>
                <group name="browBL003" />
              </group>
              <group name="browBL004_1" position={[9.84, 49.66, 64.12]} />
              <group name="MCH-nose_poffsetL" position={[8.34, 44.75, 64.67]}>
                <group name="noseL_1" />
              </group>
              <group name="MCH-nose_end_reparentL" position={[11.39, 25.51, 67.58]} />
              <group name="browBR_1" position={[-28.89, 48.45, 58.65]} />
              <group name="MCH-brow_poffsetBR001" position={[-25.64, 51.44, 62.84]}>
                <group name="browBR001_1" />
              </group>
              <group name="MCH-brow_poffsetBR002" position={[-20.43, 53.15, 65.69]}>
                <group name="browBR002_1">
                  <group name="ORG-brow_glueBR002" rotation={[0, -0.93, -0.25]} />
                </group>
              </group>
              <group name="MCH-brow_poffsetBR003" position={[-13.89, 52.69, 65.29]}>
                <group name="browBR003" />
              </group>
              <group name="browBR004_1" position={[-7.5, 49.48, 63.58]} />
              <group name="MCH-nose_poffsetR" position={[-6.25, 44.47, 65.82]}>
                <group name="noseR_1" />
              </group>
              <group name="MCH-nose_end_reparentR" position={[-9.77, 25.29, 67.66]} />
              <group name="browTL_1" position={[35.32, 46.28, 47.19]} />
              <group name="browTL001_1" position={[31.03, 51.79, 58.27]} />
              <group name="MCH-brow_reparentTL002" position={[21.54, 56.49, 66.89]} />
              <group name="MCH-brow_poffsetTL002" position={[21.54, 56.49, 66.89]}>
                <group name="browTL002_1" />
              </group>
              <group name="browTL003_1" position={[8.02, 54.72, 69.37]} />
              <group name="nose_1" position={[1.32, 49.17, 70.8]} />
              <group name="browTR_1" position={[-33.48, 49.1, 42.05]} />
              <group name="browTR001_1" position={[-29.69, 53.57, 57.2]} />
              <group name="MCH-brow_reparentTR002" position={[-19.66, 58.17, 66.74]} />
              <group name="MCH-brow_poffsetTR002" position={[-19.66, 58.17, 66.74]}>
                <group name="browTR002_1" />
              </group>
              <group name="browTR003_1" position={[-6.25, 55.47, 67.56]} />
              <group name="cheekBL_1" position={[15.57, 6.81, 62.37]} />
              <group name="MCH-cheek_reparentBL001" position={[34.52, 23.05, 48.4]} />
              <group name="MCH-cheek_poffsetBL001" position={[34.52, 23.05, 48.4]}>
                <group name="cheekBL001_1" />
              </group>
              <group name="cheekBR_1" position={[-12.88, 7.4, 63.55]} />
              <group name="MCH-cheek_reparentBR001" position={[-31.38, 23.63, 50.65]} />
              <group name="MCH-cheek_poffsetBR001" position={[-31.38, 23.63, 50.65]}>
                <group name="cheekBR001_1" />
              </group>
              <group name="cheekTL001_1" position={[20.47, 31.01, 62.4]}>
                <group name="ORG-cheek_glueTL001" rotation={[-1.49, 0.58, -0.9]} />
              </group>
              <group name="cheekTR001_1" position={[-21.93, 31.89, 57.61]}>
                <group name="ORG-cheek_glueTR001" rotation={[-1.64, -0.69, 1.02]} />
              </group>
              <group name="foreheadL_1" position={[8.39, 82.97, 63.46]} />
              <group name="foreheadL001_1" position={[22.07, 81.74, 57.38]} />
              <group name="foreheadL002_1" position={[31.39, 79.62, 49.75]} />
              <group name="foreheadR_1" position={[-4.99, 83.53, 61.35]} />
              <group name="foreheadR001_1" position={[-17.83, 83.29, 57.06]} />
              <group name="foreheadR002_1" position={[-25.91, 81.51, 49.36]} />
              <group name="jawL_1" position={[41.73, 43.99, 28.66]} />
              <group name="jawR_1" position={[-39.21, 45.76, 28.86]} />
              <group name="MCH-nose_end_glue_reparent004" position={[0.65, 6.85, 69.81]} />
              <group name="MCH-nose_glue_reparentL001" position={[8.9, 6.89, 66.38]} />
              <group name="MCH-nose_glue_reparentR001" position={[-7.23, 7.13, 66.78]} />
              <group name="MCH-nose_poffset001" position={[0.95, 35.36, 78.2]}>
                <group name="nose001_1" />
              </group>
              <group name="MCH-nose_end_reparent001" position={[0.88, 28.83, 81.77]} />
              <group name="nose_end004" position={[0.62, 17.55, 70.53]}>
                <group name="ORG-nose_end_glue004" rotation={[-3.07, 0.92, 0]} />
              </group>
              <group name="templeL_1" position={[41.55, 74.09, 36.86]} />
              <group name="templeR_1" position={[-35.57, 75.94, 36.39]} />
            </group>
          </group>
          <group name="MCH-eyeparentL" position={[16.88, 22.41, 59.27]} rotation={[-Math.PI / 2, 0, 0]}>
            <group name="eyeL_1" rotation={[Math.PI / 2, 0, 0]} />
          </group>
          <group name="MCH-eyeparentR" position={[-19.06, 22.97, 63.88]} rotation={[-Math.PI / 2, 0, 0]}>
            <group name="eyeR_1" rotation={[Math.PI / 2, 0, 0]} />
          </group>
          <group name="MCH-lip_armBL001" position={[7.5, -20.34, 30.24]} rotation={[-Math.PI / 2, 0, -3.11]}>
            <group name="MCH-lip_poffsetBL001" rotation={[-1.49, 0.03, -3.12]}>
              <group name="lipBL001" />
            </group>
          </group>
          <group name="MCH-lip_armBR001" position={[-7.1, -20.61, 30.56]} rotation={[-Math.PI / 2, 0, -3.11]}>
            <group name="MCH-lip_poffsetBR001" rotation={[-1.49, 0.03, -3.12]}>
              <group name="lipBR001" />
            </group>
          </group>
          <group name="MCH-lip_armTL001" position={[8.13, -18.25, 29.27]} rotation={[-Math.PI / 2, 0, -3.11]}>
            <group name="MCH-lip_poffsetTL001" rotation={[-1.49, 0.03, -3.12]}>
              <group name="lipTL001" />
            </group>
          </group>
          <group name="MCH-lip_armTR001" position={[-8, -18.44, 29.65]} rotation={[-Math.PI / 2, 0, -3.11]}>
            <group name="MCH-lip_poffsetTR001" rotation={[-1.49, 0.03, -3.12]}>
              <group name="lipTR001" />
            </group>
          </group>
        </group>
        <group name="r_skul">
          <primitive object={nodes.Bone} />
          <group name="SkullR">
            <skinnedMesh name="Icosphere001" geometry={nodes.Icosphere001.geometry} material={materials.hair} skeleton={nodes.Icosphere001.skeleton} />
            <skinnedMesh name="Icosphere001_1" geometry={nodes.Icosphere001_1.geometry} material={materials['FB HEAD UKRAIN']} skeleton={nodes.Icosphere001_1.skeleton} />
          </group>
        </group>
        <group name="l_skull">
          <primitive object={nodes.Bone_1} />
          <primitive object={nodes.neutral_bone} />
          <group name="SkullL">
            <skinnedMesh name="Icosphere002" geometry={nodes.Icosphere002.geometry} material={materials.hair} skeleton={nodes.Icosphere002.skeleton} />
            <skinnedMesh name="Icosphere002_1" geometry={nodes.Icosphere002_1.geometry} material={materials['FB HEAD UKRAIN']} skeleton={nodes.Icosphere002_1.skeleton} />
          </group>
        </group>
        <group name="face_deform">
          <primitive object={nodes['DEF-earL']} />
          <primitive object={nodes['DEF-earL001']} />
          <primitive object={nodes['DEF-earL002']} />
          <primitive object={nodes['DEF-earL004']} />
          <primitive object={nodes['DEF-earR']} />
          <primitive object={nodes['DEF-earR001']} />
          <primitive object={nodes['DEF-earR002']} />
          <primitive object={nodes['DEF-earR004']} />
          <primitive object={nodes['DEF-teethT']} />
          <primitive object={nodes['DEF-nose002']} />
          <primitive object={nodes['DEF-noseL001']} />
          <primitive object={nodes['DEF-noseR001']} />
          <primitive object={nodes['DEF-eye_masterL']} />
          <primitive object={nodes['DEF-lidBL']} />
          <primitive object={nodes['DEF-lidTL']} />
          <primitive object={nodes['DEF-eyeL']} />
          <primitive object={nodes['DEF-eye_masterR']} />
          <primitive object={nodes['DEF-lidBR']} />
          <primitive object={nodes['DEF-lidTR']} />
          <primitive object={nodes['DEF-eyeR']} />
          <primitive object={nodes['DEF-teethB']} />
          <primitive object={nodes['DEF-tongue']} />
          <primitive object={nodes['DEF-jaw_master']} />
          <primitive object={nodes['DEF-chin']} />
          <primitive object={nodes['DEF-jaw']} />
          <primitive object={nodes['DEF-jawL']} />
          <primitive object={nodes['DEF-jawR']} />
          <primitive object={nodes['DEF-lipTL']} />
          <primitive object={nodes['DEF-lipTR']} />
          <primitive object={nodes['DEF-lipBL']} />
          <primitive object={nodes['DEF-lipBR']} />
          <primitive object={nodes['DEF-browBL']} />
          <primitive object={nodes['DEF-browBL004']} />
          <primitive object={nodes['DEF-browBR']} />
          <primitive object={nodes['DEF-browBR004']} />
          <primitive object={nodes['DEF-browTL']} />
          <primitive object={nodes['DEF-browTL001']} />
          <primitive object={nodes['DEF-browTL003']} />
          <primitive object={nodes['DEF-browTR']} />
          <primitive object={nodes['DEF-browTR001']} />
          <primitive object={nodes['DEF-browTR003']} />
          <primitive object={nodes['DEF-cheekBL']} />
          <primitive object={nodes['DEF-cheekBR']} />
          <primitive object={nodes['DEF-cheekTL']} />
          <primitive object={nodes['DEF-cheekTR']} />
          <primitive object={nodes['DEF-foreheadL']} />
          <primitive object={nodes['DEF-foreheadL001']} />
          <primitive object={nodes['DEF-foreheadL002']} />
          <primitive object={nodes['DEF-foreheadR']} />
          <primitive object={nodes['DEF-foreheadR001']} />
          <primitive object={nodes['DEF-foreheadR002']} />
          <primitive object={nodes['DEF-nose']} />
          <primitive object={nodes['DEF-nose004']} />
          <primitive object={nodes['DEF-templeL']} />
          <primitive object={nodes['DEF-templeR']} />
          <primitive object={nodes.neutral_bone_1} />
          <group name="EyeL">
            <skinnedMesh name="Sphere002" geometry={nodes.Sphere002.geometry} material={materials.cornear} skeleton={nodes.Sphere002.skeleton} />
            <skinnedMesh name="Sphere002_1" geometry={nodes.Sphere002_1.geometry} material={materials.Eye} skeleton={nodes.Sphere002_1.skeleton} />
          </group>
          <group name="EyeR">
            <skinnedMesh name="Sphere001" geometry={nodes.Sphere001.geometry} material={materials.cornear} skeleton={nodes.Sphere001.skeleton} />
            <skinnedMesh name="Sphere001_1" geometry={nodes.Sphere001_1.geometry} material={materials.Eye} skeleton={nodes.Sphere001_1.skeleton} />
          </group>
          <skinnedMesh name="LowerTeeth" geometry={nodes.LowerTeeth.geometry} material={materials['wire_134006006.001']} skeleton={nodes.LowerTeeth.skeleton} />
          <skinnedMesh name="Tongue" geometry={nodes.Tongue.geometry} material={materials.wire_143224087} skeleton={nodes.Tongue.skeleton} />
          <skinnedMesh name="UpperTeeth" geometry={nodes.UpperTeeth.geometry} material={materials['wire_134006006.001']} skeleton={nodes.UpperTeeth.skeleton} />
          <group name="head">
            <skinnedMesh name="Icosphere" geometry={nodes.Icosphere.geometry} material={materials.Insidemouth} skeleton={nodes.Icosphere.skeleton} morphTargetDictionary={nodes.Icosphere.morphTargetDictionary} morphTargetInfluences={nodes.Icosphere.morphTargetInfluences} />
            <skinnedMesh name="Icosphere_1" geometry={nodes.Icosphere_1.geometry} material={materials.hair} skeleton={nodes.Icosphere_1.skeleton} morphTargetDictionary={nodes.Icosphere_1.morphTargetDictionary} morphTargetInfluences={nodes.Icosphere_1.morphTargetInfluences} />
            <skinnedMesh name="Icosphere_2" geometry={nodes.Icosphere_2.geometry} material={materials['FB HEAD UKRAIN']} skeleton={nodes.Icosphere_2.skeleton} morphTargetDictionary={nodes.Icosphere_2.morphTargetDictionary} morphTargetInfluences={nodes.Icosphere_2.morphTargetInfluences} />
          </group>
        </group>
        <mesh name="brain" geometry={nodes.brain.geometry} material={materials['default.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/head.glb')
